# Generated by Django 5.0.2 on 2024-03-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="subplan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("price", models.IntegerField()),
                ("max_members", models.IntegerField(null=True)),
                ("highlight_status", models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
