# Generated by Django 5.0.2 on 2024-03-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=150)),
                ("amount", models.IntegerField()),
                ("date", models.DateField(default="01-01-2024")),
            ],
        ),
    ]
