# Generated by Django 5.0.2 on 2024-03-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_wallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
