# Generated by Django 5.0.2 on 2024-03-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_wallet_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
