# Generated by Django 5.0.2 on 2024-04-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_wallet_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("duration", models.IntegerField(default=0)),
            ],
        ),
    ]
